name = "kira"
main = "src/worker.ts"
compatibility_date = "2024-11-20"
assets = { directory = "./public", binding = "ASSETS" }

[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1-sqlite"
new_sqlite_classes = ["ChatSession"]

[vars]
USE_GROQ = "true"
GROQ_MODEL = "openai/gpt-oss-20b"