name = "cf_ai_chat_memory_bot"
main = "src/worker.ts"
compatibility_date = "2024-11-20"
assets = { directory = "./public", binding = "ASSETS" }


[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]

[vars]
USE_GROQ = "true"
GROQ_MODEL = "llama-3.1-8b-instruct"